namespace Directionful.SDL.Native.Enum;

public enum EventType : uint
{
    Quit = 0x100,
    AppTerminating,
    AppLowMemory,
    AppWillEnterBackground,
    AppDidEnterBackground,
    AppWillEnterForeground,
    AppDidEnterForeground,
    LocaleChanged,
    DisplayEvent = 0x150,
    Window = 0x200,
    SysWM,
    KeyDown,
    KeyUp,
    TextEditing,
    TextInput,
    KeyMapChanged,
    TextEditingExt,
    MouseMotion = 0x400,
    MouseButtonDown,
    MouseButtonUp,
    MouseWheel,
    JoyAxisMotion = 0x600,
    JoyBallMotion,
    JoyHatMotion,
    JoyButtonDown,
    JoyButtonUp,
    JoyDeviceAdded,
    JoyDeviceRemoved,
    JoyBatteryUpdated,
    ControllerAxisMotion = 0x650,
    ControllerButtonDown,
    ControllerButtonUp,
    ControllerDeviceAdded,
    ControllerDeviceRemoved,
    ControllerDeviceRemapped,
    ControllerTouchpadDown,
    ControllerTouchpadMotion,
    ControllerTouchpadUp,
    ControllerSensorUpdate,
    FingerDown = 0x700,
    FingerUp,
    FinterMotion,
    DollarGesture = 0x800,
    DollarRecord,
    MultiGesture,
    DropFile,
    DropText,
    DropBegin,
    DropComplete,
    AudioDeviceAdded = 0x1100,
    AudioDeviceRemoved,
    SensorUpdate = 0x1200,
    RenderTargetsReset = 0x2000,
    RenderDeviceReset,
    PollSentinel = 0x7F00,
    UserEvent = 0x8000
}