name: Build (Linux)
on:
  push:
    branches-ignore: [main]
run-name: ${{github.event.head_commit.message}}
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on Ubuntu
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
      - name: Build Directionful
        run: dotnet build --project ./Directionful/Directionful.csproj