name: Name
run-name: ${{github.actor}} test
on: [workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: git fetch dev:dev
            - run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
            - run: git merge --ff-only dev
            - run: git push