name: Publish
on:
  release:
    types:
      created
jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    name: Publish on Ubuntu
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
      - name: Install requirements
        run: sudo apt-get install clang zlib1g-dev
      - name: Publish
        run: dotnet publish ./Directionful/Directionful.csproj -r linux-x64 -c Release --self-contained
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: directionful-linux
          path: Directionful/bin/Release/net7.0/linux-x64/publish
      - name: Create artifact
        run: tar -C Directionful/bin/Release/net7.0/linux-x64/publish -acvf directionful-linux.tar.gz .
      - name: Release
        run: gh release upload ${{ github.event.release.tag_name }} directionful-linux.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
  build-windows:
    runs-on: windows-latest
    name: Publish on Windows
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
      - name: Publish
        run: dotnet publish ./Directionful/Directionful.csproj -r win-x64 -c Release --self-contained
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: directionful-windows
          path: Directionful/bin/Release/net7.0/win-x64/publish
      - name: Create artifact
        run: tar -C Directionful/bin/Release/net7.0/win-x64/publish -acvf directionful-window.zip .
      - name: Release
        run: gh release upload ${{ github.event.release.tag_name }} directionful-windows.zip
        env:
          GH_TOKEN: ${{ github.token }}